### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cisso** [cisso/kayak#4]
Preparation:
- [ ] Evaluate phpdox by implementing an export to JSON and including a complete hierarchy tree. Evaluate wether raw json files are suitable as data source.
- [ ] Pick a few classes and interfaces for a combination of various aspects (obscure vs often extended/implemented, low-level vs high-level, stub docs vs extensive docs) to test what tags and more elaborate examples could look like. Get a core contributor on board if necessary.

Prototype / Alpha:
- [ ] Create a proof-of-concept UI to render a basic inheritance tree using D3js.
- [ ] Evaluate different layouts. Define, evaluate and implement basic filtering (namespace and inheritance views, zooming in on a single class or interface).
- [ ] Set up a project with the following capabilities: generate JSON, provide web frontend to navigate classes and interfaces (using the prototype code).
- [ ] Tag as alpha and publish to kayak-project.com.

Beta:
- [ ] Create a complete list of required features, expand on implementation details.
- [ ] Create and configure a drupal.org sandbox for issue sync testing.
- [ ] Implement issue editing and updating.
- [ ] Revise and update UI, create design.
- [ ] Update frontend logic.
- [ ] Update theme.
- [ ] Tag as beta and publish to kayak-project.com.

**Comment by cisso** [comment]
Focus of the alpha version will be shifting from visualizing dependencies to fuzzy search (via jsfuse) and filtering. There's just too many top level objects for a plain visualization to be useful.
